 --[[                                                                           ]]--
 --[[  Automatically generated code (do not edit)                               ]]--
 --[[                                                                           ]]--
 --[[                                                                           ]]--
 --[[  Scenario                                                                 ]]--
 --[[                                                                           ]]--
Scenario = {
  next_area_id = '5',
  --[[                                                                           ]]--
  --[[  Props                                                                    ]]--
  --[[                                                                           ]]--
  Props = {},
  --[[                                                                           ]]--
  --[[  Areas                                                                    ]]--
  --[[                                                                           ]]--
  Areas = {
    ['AREA_1'] = {
      ['rectangle'] = RECTANGLE( 300.50, 450.50, 722.50, 1024.50 ),
    },
    ['AREA_2'] = {
      ['rectangle'] = RECTANGLE( 300.50, 0.50, 722.50, 1024.50 ),
    },
  },
  --[[                                                                           ]]--
  --[[  Markers                                                                  ]]--
  --[[                                                                           ]]--
  MasterChain = {
    ['_MASTERCHAIN_'] = {
      Markers = {
        ['Mass2_9'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0.00, -0, 0 ),
          ['position'] = VECTOR3( 501.50, 18.80469, 856.50 ),
        },
        ['Mass1_1'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 529.50, 18.64844, 860.50 ),
        },
        ['Mass1_11'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 529.50, 18.64844, 852.50 ),
        },
        ['Mass4_1'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 578.50, 18.66406, 954.50 ),
        },
        ['Mass4_11'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 574.50, 18.64063, 958.50 ),
        },
        ['Mass4_4'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 570.50, 18.58594, 962.50 ),
        },
        ['Mass3_2'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 469.50, 18.67969, 928.50 ),
        },
        ['Mass2_3'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0.00, -0, 0 ),
          ['position'] = VECTOR3( 513.50, 18.78125, 852.50 ),
        },
        ['Hydrocarbon2_1'] = {
          ['size'] = FLOAT( 3.00 ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff008000' ),
          ['resource'] = BOOLEAN( true ),
          ['type'] = STRING( 'Hydrocarbon' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
          ['orientation'] = VECTOR3( 0.00, -0, 0 ),
          ['position'] = VECTOR3( 513.50, 18.5625, 866.50 ),
        },
        ['Mass1_5'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 541.50, 18.66406, 860.50 ),
        },
        ['Mass1_3'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 541.50, 18.67969, 856.50 ),
        },
        ['Mass2_5'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0.00, -0, 0 ),
          ['position'] = VECTOR3( 509.50, 18.79688, 852.50 ),
        },
        ['Mass4_2'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 566.50, 18.64844, 954.50 ),
        },
        ['Hydrocarbon3_3'] = {
          ['size'] = FLOAT( 3.00 ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff008000' ),
          ['resource'] = BOOLEAN( true ),
          ['type'] = STRING( 'Hydrocarbon' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 477.50, 18.54688, 942.50 ),
        },
        ['Mass2_8'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0.00, -0, 0 ),
          ['position'] = VECTOR3( 509.50, 18.54688, 860.50 ),
        },
        ['Mass1_4'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 537.50, 18.64844, 852.50 ),
        },
        ['Gate3'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 596.50, 18.47656, 52.50 ),
        },
        ['Mass2_6'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0.00, -0, 0 ),
          ['position'] = VECTOR3( 505.50, 18.54688, 860.50 ),
        },
        ['Hydrocarbon1_1'] = {
          ['size'] = FLOAT( 3.00 ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff008000' ),
          ['resource'] = BOOLEAN( true ),
          ['type'] = STRING( 'Hydrocarbon' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 529.50, 18.64844, 866.50 ),
        },
        ['Mass3_6'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 465.50, 18.57813, 928.50 ),
        },
        ['ARMY_1'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 535.50, 18.48438, 849.50 ),
        },
        ['Mass3_4'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 465.50, 18.65625, 932.50 ),
        },
        ['Mass3_9'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 473.50, 18.71875, 928.50 ),
        },
        ['HILL_CENTER'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 509.50, 26.48438, 992.50 ),
        },
        ['Hydrocarbon4_1'] = {
          ['size'] = FLOAT( 3.00 ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff008000' ),
          ['resource'] = BOOLEAN( true ),
          ['type'] = STRING( 'Hydrocarbon' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 566.50, 18.54688, 968.50 ),
        },
        ['Hydrocarbon3_2'] = {
          ['size'] = FLOAT( 3.00 ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff008000' ),
          ['resource'] = BOOLEAN( true ),
          ['type'] = STRING( 'Hydrocarbon' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
          ['orientation'] = VECTOR3( 0.00, -0, 0 ),
          ['position'] = VECTOR3( 471.50, 18.54688, 942.50 ),
        },
        ['Mass1_9'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 533.50, 18.66406, 856.50 ),
        },
        ['Mass3_10'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 477.50, 18.60938, 932.50 ),
        },
        ['Mass3_3'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 469.50, 18.71875, 936.50 ),
        },
        ['Mass1_8'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 529.50, 18.65625, 856.50 ),
        },
        ['ARMY_2'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0.00, -0, 0 ),
          ['position'] = VECTOR3( 507.50, 19.1875, 849.50 ),
        },
        ['Mass4_8'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 574.50, 18.60938, 962.50 ),
        },
        ['Mass4_3'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 566.50, 18.57813, 962.50 ),
        },
        ['Hydrocarbon2_3'] = {
          ['size'] = FLOAT( 3.00 ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff008000' ),
          ['resource'] = BOOLEAN( true ),
          ['type'] = STRING( 'Hydrocarbon' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 501.50, 18.53125, 866.50 ),
        },
        ['Gate9'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 526.50, 18.84375, 137.50 ),
        },
        ['Hydrocarbon4_3'] = {
          ['size'] = FLOAT( 3.00 ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff008000' ),
          ['resource'] = BOOLEAN( true ),
          ['type'] = STRING( 'Hydrocarbon' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 578.50, 18.57813, 968.50 ),
        },
        ['Mass3_1'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 477.50, 18.97656, 928.50 ),
        },
        ['Mass2_7'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0.00, -0, 0 ),
          ['position'] = VECTOR3( 501.50, 18.9375, 852.50 ),
        },
        ['Mass4_10'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 578.50, 18.64844, 958.50 ),
        },
        ['Gate6'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 689.50, 20.47656, 79.50 ),
        },
        ['Hydrocarbon3_1'] = {
          ['size'] = FLOAT( 3.00 ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff008000' ),
          ['resource'] = BOOLEAN( true ),
          ['type'] = STRING( 'Hydrocarbon' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 465.50, 18.67969, 942.50 ),
        },
        ['Mass4_12'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 578.50, 18.625, 962.50 ),
        },
        ['Gate4'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 358.50, 18.57031, 60.50 ),
        },
        ['Hydrocarbon1_3'] = {
          ['size'] = FLOAT( 3.00 ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff008000' ),
          ['resource'] = BOOLEAN( true ),
          ['type'] = STRING( 'Hydrocarbon' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 541.50, 18.875, 866.50 ),
        },
        ['Gate8'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 455.50, 19.26563, 166.50 ),
        },
        ['Hydrocarbon2_2'] = {
          ['size'] = FLOAT( 3.00 ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff008000' ),
          ['resource'] = BOOLEAN( true ),
          ['type'] = STRING( 'Hydrocarbon' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
          ['orientation'] = VECTOR3( 0.00, -0, 0 ),
          ['position'] = VECTOR3( 507.50, 18.54688, 866.50 ),
        },
        ['Mass2_11'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0.00, -0, 0 ),
          ['position'] = VECTOR3( 513.50, 18.5625, 856.50 ),
        },
        ['Mass3_12'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 477.50, 18.52344, 936.50 ),
        },
        ['Mass2_2'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0.00, -0, 0 ),
          ['position'] = VECTOR3( 513.50, 18.57031, 860.50 ),
        },
        ['Gate1'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 450.50, 18.64844, 69.50 ),
        },
        ['ARMY_4'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 572.50, 18.66406, 950.50 ),
        },
        ['Mass2_4'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0.00, -0, 0 ),
          ['position'] = VECTOR3( 505.50, 18.64063, 856.50 ),
        },
        ['Mass1_7'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 533.50, 18.66406, 860.50 ),
        },
        ['Mass3_11'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 473.50, 18.60938, 936.50 ),
        },
        ['Mass2_10'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0.00, -0, 0 ),
          ['position'] = VECTOR3( 505.50, 18.92188, 852.50 ),
        },
        ['ARMY_3'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 471.50, 18.71875, 924.50 ),
        },
        ['Mass4_6'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 570.50, 18.64844, 954.50 ),
        },
        ['Hydrocarbon4_2'] = {
          ['size'] = FLOAT( 3.00 ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff008000' ),
          ['resource'] = BOOLEAN( true ),
          ['type'] = STRING( 'Hydrocarbon' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 572.50, 18.55469, 968.50 ),
        },
        ['Gate5'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 323.50, 18.67188, 121.50 ),
        },
        ['Mass3_8'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 465.50, 18.82031, 936.50 ),
        },
        ['Gate2'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 532.50, 18.57031, 89.50 ),
        },
        ['Mass2_1'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0.00, -0, 0 ),
          ['position'] = VECTOR3( 509.50, 18.53125, 856.50 ),
        },
        ['Mass3_7'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 469.50, 18.71094, 932.50 ),
        },
        ['Hydrocarbon1_2'] = {
          ['size'] = FLOAT( 3.00 ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff008000' ),
          ['resource'] = BOOLEAN( true ),
          ['type'] = STRING( 'Hydrocarbon' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 535.50, 18.6875, 866.50 ),
        },
        ['Mass2_12'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 501.50, 18.67969, 860.50 ),
        },
        ['Mass4_5'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 570.50, 18.625, 958.50 ),
        },
        ['Mass4_9'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 566.50, 18.61719, 958.50 ),
        },
        ['Mass1_10'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 541.50, 18.67969, 852.50 ),
        },
        ['Mass1_6'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 533.50, 18.65625, 852.50 ),
        },
        ['Mass3_5'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 473.50, 18.65625, 932.50 ),
        },
        ['Mass1_12'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 537.50, 18.66406, 860.50 ),
        },
        ['Mass4_7'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 574.50, 18.65625, 954.50 ),
        },
        ['Gate7'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 697.50, 21.48438, 133.50 ),
        },
        ['Mass1_2'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 537.50, 18.66406, 856.50 ),
        },
        ['Combat Zone 01'] = {
          ['type'] = STRING( 'Combat Zone' ),
          ['position'] = VECTOR3( 457.50, 19.3125, 170.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
        },
        ['Combat Zone 02'] = {
          ['type'] = STRING( 'Combat Zone' ),
          ['position'] = VECTOR3( 509.50, 18.50781, 534.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
        },
        ['Combat Zone 03'] = {
          ['type'] = STRING( 'Combat Zone' ),
          ['position'] = VECTOR3( 539.50, 18.47656, 362.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
        },
        ['Combat Zone 04'] = {
          ['type'] = STRING( 'Combat Zone' ),
          ['position'] = VECTOR3( 498.50, 18.67969, 680.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
        },
        ['Combat Zone 05'] = {
          ['type'] = STRING( 'Combat Zone' ),
          ['position'] = VECTOR3( 503.50, 18.67969, 281.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
        },
        ['Combat Zone 06'] = {
          ['type'] = STRING( 'Combat Zone' ),
          ['position'] = VECTOR3( 328.50, 18.67969, 126.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
        },
        ['Defensive Point 01'] = {
          ['type'] = STRING( 'Defensive Point' ),
          ['position'] = VECTOR3( 532.50, 18.67969, 761.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
        },
        ['Rally Point 01'] = {
          ['type'] = STRING( 'Rally Point' ),
          ['position'] = VECTOR3( 517.50, 18.66406, 731.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'FF808000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
        },
        ['Defensive Point 02'] = {
          ['type'] = STRING( 'Defensive Point' ),
          ['position'] = VECTOR3( 501.50, 18.80469, 762.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
        },
        ['Rally Point 02'] = {
          ['type'] = STRING( 'Rally Point' ),
          ['position'] = VECTOR3( 475.50, 19.38281, 638.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'FF808000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
        },
        ['Protected Experimental Construction 01'] = {
          ['type'] = STRING( 'Protected Experimental Construction' ),
          ['position'] = VECTOR3( 535.50, 18.67969, 873.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
        },
        ['Protected Experimental Construction 02'] = {
          ['type'] = STRING( 'Protected Experimental Construction' ),
          ['position'] = VECTOR3( 507.50, 18.53125, 874.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
        },
        ['Protected Experimental Construction 03'] = {
          ['type'] = STRING( 'Protected Experimental Construction' ),
          ['position'] = VECTOR3( 471.50, 18.52344, 947.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
        },
        ['Protected Experimental Construction 04'] = {
          ['type'] = STRING( 'Protected Experimental Construction' ),
          ['position'] = VECTOR3( 572.50, 18.54688, 973.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
        },
        ['LandPN02'] = {
          ['type'] = STRING( 'Land Path Node' ),
          ['position'] = VECTOR3( 530.50, 18.67188, 348.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultLand' ),
          ['adjacentTo'] = STRING( 'LandPN01 LandPN03' ),
          ['color'] = STRING( 'ff00ff00' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['LandPN01'] = {
          ['type'] = STRING( 'Land Path Node' ),
          ['position'] = VECTOR3( 498.50, 19.36719, 199.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultLand' ),
          ['adjacentTo'] = STRING( 'LandPN02 LandPN08 LandPN09 LandPN10' ),
          ['color'] = STRING( 'ff00ff00' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['LandPN03'] = {
          ['type'] = STRING( 'Land Path Node' ),
          ['position'] = VECTOR3( 498.50, 19.375, 629.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultLand' ),
          ['adjacentTo'] = STRING( 'LandPN02 LandPN11' ),
          ['color'] = STRING( 'ff00ff00' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AmphPN01'] = {
          ['type'] = STRING( 'Amphibious Path Node' ),
          ['position'] = VECTOR3( 667.50, 17.50, 778.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAmphibious' ),
          ['adjacentTo'] = STRING( 'AmphPN07 AmphPN10' ),
          ['color'] = STRING( 'ff00ffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AmphPN02'] = {
          ['type'] = STRING( 'Amphibious Path Node' ),
          ['position'] = VECTOR3( 510.50, 19.33594, 548.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAmphibious' ),
          ['adjacentTo'] = STRING( 'AmphPN05 AmphPN06 AmphPN11 AmphPN15' ),
          ['color'] = STRING( 'ff00ffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['LandPN04'] = {
          ['type'] = STRING( 'Land Path Node' ),
          ['position'] = VECTOR3( 521.50, 19.14844, 801.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultLand' ),
          ['adjacentTo'] = STRING( 'LandPN05 LandPN06 LandPN07 LandPN11' ),
          ['color'] = STRING( 'ff00ff00' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['LandPN05'] = {
          ['type'] = STRING( 'Land Path Node' ),
          ['position'] = VECTOR3( 403.50, 18.47656, 878.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultLand' ),
          ['adjacentTo'] = STRING( 'LandPN04 LandPN07' ),
          ['color'] = STRING( 'ff00ff00' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['LandPN06'] = {
          ['type'] = STRING( 'Land Path Node' ),
          ['position'] = VECTOR3( 633.50, 18.67969, 875.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultLand' ),
          ['adjacentTo'] = STRING( 'LandPN04 LandPN07' ),
          ['color'] = STRING( 'ff00ff00' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['LandPN07'] = {
          ['type'] = STRING( 'Land Path Node' ),
          ['position'] = VECTOR3( 519.50, 26.45313, 997.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultLand' ),
          ['adjacentTo'] = STRING( 'LandPN04 LandPN05 LandPN06' ),
          ['color'] = STRING( 'ff00ff00' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['LandPN08'] = {
          ['type'] = STRING( 'Land Path Node' ),
          ['position'] = VECTOR3( 625.50, 18.47656, 137.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultLand' ),
          ['adjacentTo'] = STRING( 'LandPN01 LandPN10' ),
          ['color'] = STRING( 'ff00ff00' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['LandPN09'] = {
          ['type'] = STRING( 'Land Path Node' ),
          ['position'] = VECTOR3( 335.50, 18.58594, 106.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultLand' ),
          ['adjacentTo'] = STRING( 'LandPN01 LandPN10' ),
          ['color'] = STRING( 'ff00ff00' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['LandPN10'] = {
          ['type'] = STRING( 'Land Path Node' ),
          ['position'] = VECTOR3( 504.50, 19.03125, 98.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultLand' ),
          ['adjacentTo'] = STRING( 'LandPN01 LandPN08 LandPN09' ),
          ['color'] = STRING( 'ff00ff00' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AirPN01'] = {
          ['type'] = STRING( 'Air Path Node' ),
          ['position'] = VECTOR3( 507.50, 18.67969, 716.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAir' ),
          ['adjacentTo'] = STRING( 'AirPN02 AirPN03 AirPN04 AirPN05 AirPN09 AirPN10' ),
          ['color'] = STRING( 'ffffffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AirPN02'] = {
          ['type'] = STRING( 'Air Path Node' ),
          ['position'] = VECTOR3( 507.50, 18.94531, 346.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAir' ),
          ['adjacentTo'] = STRING( 'AirPN01 AirPN06 AirPN07 AirPN08 AirPN09 AirPN10' ),
          ['color'] = STRING( 'ffffffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AirPN03'] = {
          ['type'] = STRING( 'Air Path Node' ),
          ['position'] = VECTOR3( 646.50, 18.03906, 823.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAir' ),
          ['adjacentTo'] = STRING( 'AirPN01 AirPN05 AirPN09' ),
          ['color'] = STRING( 'ffffffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AirPN04'] = {
          ['type'] = STRING( 'Air Path Node' ),
          ['position'] = VECTOR3( 391.50, 20.78125, 830.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAir' ),
          ['adjacentTo'] = STRING( 'AirPN01 AirPN05 AirPN10' ),
          ['color'] = STRING( 'ffffffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AirPN05'] = {
          ['type'] = STRING( 'Air Path Node' ),
          ['position'] = VECTOR3( 513.50, 24.57031, 973.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAir' ),
          ['adjacentTo'] = STRING( 'AirPN01 AirPN03 AirPN04' ),
          ['color'] = STRING( 'ffffffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AirPN06'] = {
          ['type'] = STRING( 'Air Path Node' ),
          ['position'] = VECTOR3( 388.50, 18.6875, 198.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAir' ),
          ['adjacentTo'] = STRING( 'AirPN02 AirPN08 AirPN10' ),
          ['color'] = STRING( 'ffffffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AirPN07'] = {
          ['type'] = STRING( 'Air Path Node' ),
          ['position'] = VECTOR3( 626.50, 21.29688, 193.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAir' ),
          ['adjacentTo'] = STRING( 'AirPN02 AirPN08 AirPN09' ),
          ['color'] = STRING( 'ffffffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AirPN08'] = {
          ['type'] = STRING( 'Air Path Node' ),
          ['position'] = VECTOR3( 506.50, 18.57813, 149.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAir' ),
          ['adjacentTo'] = STRING( 'AirPN02 AirPN06 AirPN07' ),
          ['color'] = STRING( 'ffffffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AmphPN03'] = {
          ['type'] = STRING( 'Amphibious Path Node' ),
          ['position'] = VECTOR3( 483.50, 18.75781, 139.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAmphibious' ),
          ['adjacentTo'] = STRING( 'AmphPN04 AmphPN12 AmphPN13 AmphPN16' ),
          ['color'] = STRING( 'ff00ffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AmphPN04'] = {
          ['type'] = STRING( 'Amphibious Path Node' ),
          ['position'] = VECTOR3( 360.50, 17.50, 239.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAmphibious' ),
          ['adjacentTo'] = STRING( 'AmphPN03 AmphPN14' ),
          ['color'] = STRING( 'ff00ffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AmphPN05'] = {
          ['type'] = STRING( 'Amphibious Path Node' ),
          ['position'] = VECTOR3( 419.50, 17.50, 476.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAmphibious' ),
          ['adjacentTo'] = STRING( 'AmphPN02 AmphPN11 AmphPN14' ),
          ['color'] = STRING( 'ff00ffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AmphPN06'] = {
          ['type'] = STRING( 'Amphibious Path Node' ),
          ['position'] = VECTOR3( 613.50, 17.50, 541.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAmphibious' ),
          ['adjacentTo'] = STRING( 'AmphPN02 AmphPN10 AmphPN11' ),
          ['color'] = STRING( 'ff00ffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AmphPN07'] = {
          ['type'] = STRING( 'Amphibious Path Node' ),
          ['position'] = VECTOR3( 522.50, 18.61719, 911.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAmphibious' ),
          ['adjacentTo'] = STRING( 'AmphPN01 AmphPN08 AmphPN09 AmphPN15' ),
          ['color'] = STRING( 'ff00ffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AmphPN08'] = {
          ['type'] = STRING( 'Amphibious Path Node' ),
          ['position'] = VECTOR3( 704.50, 17.50, 801.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAmphibious' ),
          ['adjacentTo'] = STRING( 'AmphPN07 AmphPN10' ),
          ['color'] = STRING( 'ff00ffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AmphPN09'] = {
          ['type'] = STRING( 'Amphibious Path Node' ),
          ['position'] = VECTOR3( 628.50, 17.50, 756.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAmphibious' ),
          ['adjacentTo'] = STRING( 'AmphPN07 AmphPN10' ),
          ['color'] = STRING( 'ff00ffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AmphPN10'] = {
          ['type'] = STRING( 'Amphibious Path Node' ),
          ['position'] = VECTOR3( 645.50, 17.50, 634.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAmphibious' ),
          ['adjacentTo'] = STRING( 'AmphPN01 AmphPN06 AmphPN08 AmphPN09' ),
          ['color'] = STRING( 'ff00ffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AmphPN11'] = {
          ['type'] = STRING( 'Amphibious Path Node' ),
          ['position'] = VECTOR3( 515.50, 18.97656, 481.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAmphibious' ),
          ['adjacentTo'] = STRING( 'AmphPN02 AmphPN05 AmphPN06 AmphPN16' ),
          ['color'] = STRING( 'ff00ffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AmphPN12'] = {
          ['type'] = STRING( 'Amphibious Path Node' ),
          ['position'] = VECTOR3( 317.50, 17.50, 212.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAmphibious' ),
          ['adjacentTo'] = STRING( 'AmphPN03 AmphPN14' ),
          ['color'] = STRING( 'ff00ffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AmphPN13'] = {
          ['type'] = STRING( 'Amphibious Path Node' ),
          ['position'] = VECTOR3( 401.50, 17.50, 273.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAmphibious' ),
          ['adjacentTo'] = STRING( 'AmphPN03 AmphPN14' ),
          ['color'] = STRING( 'ff00ffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AmphPN14'] = {
          ['type'] = STRING( 'Amphibious Path Node' ),
          ['position'] = VECTOR3( 366.50, 17.50, 391.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAmphibious' ),
          ['adjacentTo'] = STRING( 'AmphPN04 AmphPN05 AmphPN12 AmphPN13' ),
          ['color'] = STRING( 'ff00ffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AmphPN15'] = {
          ['type'] = STRING( 'Amphibious Path Node' ),
          ['position'] = VECTOR3( 510.50, 18.67188, 741.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAmphibious' ),
          ['adjacentTo'] = STRING( 'AmphPN02 AmphPN07' ),
          ['color'] = STRING( 'ff00ffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AmphPN16'] = {
          ['type'] = STRING( 'Amphibious Path Node' ),
          ['position'] = VECTOR3( 512.50, 18.67969, 286.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAmphibious' ),
          ['adjacentTo'] = STRING( 'AmphPN03 AmphPN11' ),
          ['color'] = STRING( 'ff00ffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AirPN09'] = {
          ['type'] = STRING( 'Air Path Node' ),
          ['position'] = VECTOR3( 654.50, 17.50, 543.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAir' ),
          ['adjacentTo'] = STRING( 'AirPN01 AirPN02 AirPN03 AirPN07 AirPN10' ),
          ['color'] = STRING( 'ffffffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['AirPN10'] = {
          ['type'] = STRING( 'Air Path Node' ),
          ['position'] = VECTOR3( 380.50, 17.50, 497.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultAir' ),
          ['adjacentTo'] = STRING( 'AirPN01 AirPN02 AirPN04 AirPN06 AirPN09' ),
          ['color'] = STRING( 'ffffffff' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['Rally Point 03'] = {
          ['type'] = STRING( 'Rally Point' ),
          ['position'] = VECTOR3( 535.50, 19.70313, 389.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'FF808000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
        },
        ['Defensive Point 03'] = {
          ['type'] = STRING( 'Defensive Point' ),
          ['position'] = VECTOR3( 526.50, 18.66406, 414.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
        },
        ['Combat Zone 07'] = {
          ['type'] = STRING( 'Combat Zone' ),
          ['position'] = VECTOR3( 360.50, 18.57813, 67.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
        },
        ['Combat Zone 08'] = {
          ['type'] = STRING( 'Combat Zone' ),
          ['position'] = VECTOR3( 450.50, 18.66406, 76.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
        },
        ['Combat Zone 09'] = {
          ['type'] = STRING( 'Combat Zone' ),
          ['position'] = VECTOR3( 593.50, 18.48438, 57.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
        },
        ['Combat Zone 10'] = {
          ['type'] = STRING( 'Combat Zone' ),
          ['position'] = VECTOR3( 530.50, 19.20313, 95.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
        },
        ['Combat Zone 11'] = {
          ['type'] = STRING( 'Combat Zone' ),
          ['position'] = VECTOR3( 525.50, 18.42188, 142.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
        },
        ['Combat Zone 12'] = {
          ['type'] = STRING( 'Combat Zone' ),
          ['position'] = VECTOR3( 688.50, 20.46875, 83.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
        },
        ['Combat Zone 13'] = {
          ['type'] = STRING( 'Combat Zone' ),
          ['position'] = VECTOR3( 695.50, 21.48438, 137.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
        },
        ['Rally Point 04'] = {
          ['type'] = STRING( 'Rally Point' ),
          ['position'] = VECTOR3( 504.50, 19.05469, 224.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'FF808000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
        },
        ['Rally Point 05'] = {
          ['type'] = STRING( 'Rally Point' ),
          ['position'] = VECTOR3( 370.50, 19.20313, 111.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'FF808000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
        },
        ['Rally Point 06'] = {
          ['type'] = STRING( 'Rally Point' ),
          ['position'] = VECTOR3( 663.50, 18.92188, 130.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'FF808000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
        },
        ['Rally Point 07'] = {
          ['type'] = STRING( 'Rally Point' ),
          ['position'] = VECTOR3( 540.50, 19.1875, 119.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'FF808000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
        },
        ['LandPN11'] = {
          ['type'] = STRING( 'Land Path Node' ),
          ['position'] = VECTOR3( 518.50, 18.71094, 707.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['graph'] = STRING( 'DefaultLand' ),
          ['adjacentTo'] = STRING( 'LandPN03 LandPN04' ),
          ['color'] = STRING( 'ff00ff00' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
        },
        ['Rally Point 08'] = {
          ['type'] = STRING( 'Rally Point' ),
          ['position'] = VECTOR3( 455.50, 18.82031, 123.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'FF808000' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
        },
      },
    },
  },
  Chains = {
    ['LandPatrolChain'] = {
      Markers = {'LandPN01', 'LandPN02', 'LandPN03', 'LandPN11', 'LandPN04', 'LandPN07', 'LandPN05', 'LandPN06'},
    },
    ['AirPatrolChain'] = {
      Markers = {'AirPN08', 'AirPN02', 'AirPN01', 'AirPN05'},
    },
  },
  --[[                                                                           ]]--
  --[[  Orders                                                                   ]]--
  --[[                                                                           ]]--
  next_queue_id = '1',
  Orders = {},
  --[[                                                                           ]]--
  --[[  Platoons                                                                 ]]--
  --[[                                                                           ]]--
  next_platoon_id = '1',
  Platoons = {},
  --[[                                                                           ]]--
  --[[  Armies                                                                   ]]--
  --[[                                                                           ]]--
  next_army_id = '5',
  next_group_id = '1',
  next_unit_id = '2',
  Armies = {
    --[[                                                                           ]]--
    --[[  Army                                                                     ]]--
    --[[                                                                           ]]--
    ['ARMY_3'] = {
      personality = '',
      plans = '',
      color = 0,
      faction = 0,
      Economy = {mass = 0, energy = 0},
      Alliances = {},
      ['Units'] = GROUP {
        orders = '',
        platoon = '',
        Units = {
          ['INITIAL'] = GROUP {
            orders = '',
            platoon = '',
            Units = {},
          },
        },
      },
      PlatoonBuilders = {
        next_platoon_builder_id = '0',
        Builders = {},
      },
    },
    --[[                                                                           ]]--
    --[[  Army                                                                     ]]--
    --[[                                                                           ]]--
    ['ARMY_1'] = {
      personality = '',
      plans = '',
      color = 0,
      faction = 0,
      Economy = {mass = 0, energy = 0},
      Alliances = {},
      ['Units'] = GROUP {
        orders = '',
        platoon = '',
        Units = {
          ['INITIAL'] = GROUP {
            orders = '',
            platoon = '',
            Units = {},
          },
        },
      },
      PlatoonBuilders = {
        next_platoon_builder_id = '0',
        Builders = {},
      },
    },
    --[[                                                                           ]]--
    --[[  Army                                                                     ]]--
    --[[                                                                           ]]--
    ['ARMY_INCOMING_ENEMY'] = {
      personality = '',
      plans = '',
      color = 0,
      faction = 0,
      Economy = {mass = 0, energy = 0},
      Alliances = {},
      ['Units'] = GROUP {
        orders = '',
        platoon = '',
        Units = {
          ['INITIAL'] = GROUP {
            orders = '',
            platoon = '',
            Units = {},
          },
        },
      },
      PlatoonBuilders = {
        next_platoon_builder_id = '0',
        Builders = {},
      },
    },
    --[[                                                                           ]]--
    --[[  Army                                                                     ]]--
    --[[                                                                           ]]--
    ['ARMY_4'] = {
      personality = '',
      plans = '',
      color = 0,
      faction = 0,
      Economy = {mass = 0, energy = 0},
      Alliances = {},
      ['Units'] = GROUP {
        orders = '',
        platoon = '',
        Units = {
          ['INITIAL'] = GROUP {
            orders = '',
            platoon = '',
            Units = {},
          },
        },
      },
      PlatoonBuilders = {
        next_platoon_builder_id = '0',
        Builders = {},
      },
    },
    --[[                                                                           ]]--
    --[[  Army                                                                     ]]--
    --[[                                                                           ]]--
    ['ARMY_HQ'] = {
      personality = '',
      plans = '',
      color = 0,
      faction = 0,
      Economy = {mass = 0, energy = 0},
      Alliances = {},
      ['Units'] = GROUP {
        orders = '',
        platoon = '',
        Units = {
          ['INITIAL'] = GROUP {
            orders = '',
            platoon = '',
            Units = {},
          },
        },
      },
      PlatoonBuilders = {
        next_platoon_builder_id = '1',
        Builders = {},
      },
    },
    --[[                                                                           ]]--
    --[[  Army                                                                     ]]--
    --[[                                                                           ]]--
    ['ARMY_2'] = {
      personality = '',
      plans = '',
      color = 0,
      faction = 0,
      Economy = {mass = 0, energy = 0},
      Alliances = {},
      ['Units'] = GROUP {
        orders = '',
        platoon = '',
        Units = {
          ['INITIAL'] = GROUP {
            orders = '',
            platoon = '',
            Units = {},
          },
        },
      },
      PlatoonBuilders = {
        next_platoon_builder_id = '0',
        Builders = {},
      },
    },
    ['ARMY_9'] = {
      personality = '',
      plans = '',
      color = 0,
      faction = 0,
      Economy = {mass = 0, energy = 0},
      Alliances = {},
      ['Units'] = GROUP {
        orders = '',
        platoon = '',
        Units = {
          ['INITIAL'] = GROUP {
            orders = '',
            platoon = '',
            Units = {},
          },
        },
      },
      PlatoonBuilders = {
        next_platoon_builder_id = 0,
        Builders = {},
      },
    },
    ['NEUTRAL_CIVILIAN'] = {
      personality = '',
      plans = '',
      color = 0,
      faction = 0,
      Economy = {mass = 0, energy = 0},
      Alliances = {},
      ['Units'] = GROUP {
        orders = '',
        platoon = '',
        Units = {
          ['INITIAL'] = GROUP {
            orders = '',
            platoon = '',
            Units = {},
          },
        },
      },
      PlatoonBuilders = {
        next_platoon_builder_id = 0,
        Builders = {},
      },
    },
  },
}
